# Generated by Django 3.0.3 on 2020-02-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('SeasonID', models.IntegerField()),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('ParentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonName', models.CharField(blank=True, default='', max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['StartDate'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonl.Customers')),
                ('SeasonID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasonl.Season')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSummaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalRepaid', models.FloatField()),
                ('TotalCredit', models.FloatField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonl.Customers')),
                ('SeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonl.Season')),
            ],
        ),
    ]
