# Generated by Django 3.0.3 on 2020-02-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonl.Customers'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='ParentID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='SeasonID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasonl.Season'),
        ),
    ]
